### ISSUE TITLE
Buttons greyed out and no botname in list

### ISSUE THREAD

**Issue by claell** [alvr/ASFui#1]
I just tried to set this up, but cannot get it to work properly I guess. I set up the path to ASF.exe and set up ASF as described here: https://github.com/JustArchi/ArchiSteamFarm/wiki/Setting-up
Also now I have set the Steam owner ID, but still the GUI is not really working.

**Comment by claell** [comment]
Nevermind, seems I had to press the reload button next to the bot list (although I thought I have tried that already). Seems to work now.

Probably one needs to press the reload button after ASF has successfully started and checked the steam pages.

**Comment by alvr** [comment]
@claell The bot list is loaded after one second of clicking the Start button. If ASF is not loaded completely it will not reload the bot list, so you need to click on the reload button.

I will increase it to 2 seconds, so it might be loaded completely.

**Comment by claell** [comment]
This is probably the reason. I have a rather large library and ASF needs to load 2 pages of cards. Might it be better to check whether ASF is loaded completely by checking the log output instead of adding a time threshold?

**Comment by claell** [comment]
Just noticed that it has nothing to do with the amount of pages with badges that ASF needs to load, because it is already completely loaded before.
