### ISSUE TITLE
CRITICAL put back "https://raw.githubusercontent.com/alvr/ASFui/master/version.txt"

### ISSUE THREAD

**Issue by KlappPc** [alvr/ASFui#19]
For the time being put that page back up.

Unchaught Web.Exeption in all versions. I.E. no ASFui is starting anymore.

**Comment by alvr** [comment]
Forgot about it. Now that ASF v3 will become multi-platform, I'm porting ASFui to Kotlin/JavaFX.

**Comment by KlappPc** [comment]
Jeha noticed that ;->

Was just damm confused, why now all version break and though I fucked up a merge or something ^^.

You should catch that check in the new version. Github might be down or something.
