### ISSUE TITLE
buttons don't  work

### ISSUE THREAD

**Issue by RandomUser46513521** [alvr/ASFui#3]
All the buttons are grayed out ie (Input, Cards, Keys, Games, Chat, Manage Bots, ArchiSteamFarm, 2FA)
I am using ASFui v0.3.9.0 and ASF V2.1.6.3
![capture](https://cloud.githubusercontent.com/assets/23127112/19818934/bfc41326-9d17-11e6-8ff2-15625fff34fc.PNG)

**Comment by alvr** [comment]
Have you tried few more times? It should fetch the bot list when, at least, a bot is logged in.

This is the first time someone report this issue. It was implemented in [0.3.6](https://github.com/alvr/ASFui/commit/0b261b4e0224ee8fa55230703ac8b7f3c74694b0#diff-9919a60f763a8dfe576baaa42038c47fR127) but no one had this problem.

**Comment by RandomUser46513521** [comment]
I have now tried with many different combinations for ASF versions and ASFui versions and it still stays grayed out. For some reason all versions seem to be broken now. I think it might be because the bots.bin files. It just started happening when I switched to ASFui v0.3.9.0 and the newest ASF v2.1.6.3

**Comment by RandomUser46513521** [comment]
Well it was not he bin files. I completely re-downloaded both ASF and ASFui and re-setup some of my bots and it is still all grayed out. I really have no idea what the problem is considering it worked before.

**Comment by alvr** [comment]
@RandomUser46513521 If you click the reload button it works?

**Comment by RandomUser46513521** [comment]
Nope. The reload button doesn't work. I tried using a older version of the ui (3.8) with the latest version of ASF and it is still broken.

**Comment by alvr** [comment]
Try v0.4.1, but first delete uiLog.txt, where ASFui is located, then start ASFui.

Open uiLog.txt and find _Bot list refreshed. Detected X bots._

If X == 0, try renaming your bots.

**Comment by RandomUser46513521** [comment]
I don't see any uilog.txt file anywhere.

**Comment by RandomUser46513521** [comment]
Tried re downloading and setting up ASF and ASFui and no buttons work still.

**Comment by iHyper445** [comment]
I have the exact same issue; I downloaded the newest version of ASF and ASFui, and then the buttons just stopped working. They worked great before but now the refresh button does nothing and all the buttons are grayed out.

**Comment by iHyper445** [comment]
I figured it out @RandomUser46513521 
I went back to the SteamGifts forum post [ https://www.steamgifts.com/discussion/eT97I/asfui-archisteamfarm-user-interface ] and saw that one of the steps was to put in your SteamOwnerID value in (Steam64 ID)

http://steamid.co/
Just go here, copy and paste your profile link into the box, copy your Steam64 ID and then place it in the respective cell in the ASF-Config

Once that is in the config, it should work just fine.

**Comment by RandomUser46513521** [comment]
I already had my Steam64 ID in all my bots. Everything worked before but it stopped working when I updated to v3.9 and no longer works with older versions either. @iHyper445

**Comment by RandomUser46513521** [comment]
Yes this fixed it. Strange that it worked on older versions without my ID there.
