### ISSUE TITLE
Make !pause^ the default Pause.

### ISSUE THREAD

**Issue by Luckz** [alvr/ASFui#5]
https://github.com/JustArchi/ArchiSteamFarm/wiki/Commands

I was just troubled by https://github.com/JustArchi/ArchiSteamFarm/issues/367 , and as far as I can see I can't manually send commands with ASFui (was this a feature in the very early releases?).

**Comment by alvr** [comment]
Sorry for the delay. Added in b357a40d and available in v0.5.0
