### ISSUE TITLE
ASFui crashing with ASF V2.1.7.6 

### ISSUE THREAD

**Issue by ezelkow1** [alvr/ASFui#6]
ASF's latest update looks like it causes some issues for ASFui. Mine crashes while ASF is still coming up, and it leaves ASF still running in the background

**Comment by JustArchi** [comment]
https://github.com/KlappPc/ASFui/commit/6df027b9b4268f73a6562f254e30332ac8a64ea0 should be enough.

**Comment by iHyper445** [comment]
Exact same thing happens to me! I noticed it when I tried to run it today and after the first bot loads in, the program stops working. It must be something with the new ASF update, hopefully the issue can be resolved soon.
(Image is ASF running in the background after crash.)
![image](https://cloud.githubusercontent.com/assets/23282217/21250331/86a326bc-c301-11e6-9772-82f9a626f53e.png)

**Comment by jaguarmoves** [comment]
@JustArchi i dont have visual studio
update is the best

**Comment by r6d2** [comment]
Same thing here. I tried a clean install as well of both ASF & ASFui with 1 bot only and minimal settings. Still crashing shortly after starting and leaving a deamon process behind.

ASF alone works OK though.

**Comment by alvr** [comment]
Fixed in #7. Released 0.5.0

**Comment by jaguarmoves** [comment]
@alvr thank you
